### ISSUE TITLE
Activating User generates timeout

### ISSUE THREAD

**Issue by homebrewhops** [ilosuna/mylittleforum#301] opened 2017-12-08 17:38 UTC
Admins when clicking the Activate User link generates a timeout. I'm doing this because users are claiming the activate link also generates a timeout, but I can't line up the timestamps.

This is what is found at the timestamp in apache logs when I press Activate user:
```
[Fri Dec 08 12:31:05.760742 2017] [:error] [pid 19050] [client 10.2.1.30:38850] PHP Notice:  Undefined index: admin_activate_user_email_text in /var/www/website/board/includes/admin.inc.php on line 729, referer: https://fqdn/board/index.php?mode=admin&edit_user=7
[Fri Dec 08 12:31:05.760813 2017] [:error] [pid 19050] [client 10.2.1.30:38850] PHP Notice:  Undefined index: admin_activate_user_email_subj in /var/www/website/board/includes/admin.inc.php on line 731, referer: https://fqdn/board/index.php?mode=admin&edit_user=7
```

The end result is that the user becomes activated and the admin page needs to be refreshed.

**Comment by derletztekick** [comment] 2017-12-08 19:25
Hi homebrewhops,

can you check the following modification and report the results?

**admin.inc.php**
look for lines 729/730, i.e.:
```
		$lang['admin_activate_user_email_text'] = str_replace("[name]", htmlspecialchars($field['user_name']), $lang['admin_activate_user_email_text']);
		$lang['admin_activate_user_email_text'] = str_replace("[login_link]", $settings['forum_address']."index.php?mode=login", $lang['admin_activate_user_email_text']);
```

and change it to:

```
		$smarty->configLoad($settings['language_file'], 'emails');
		$lang = $smarty->getConfigVars();
		$lang['admin_activate_user_email_text'] = str_replace("[name]", htmlspecialchars($field['user_name']), $lang['admin_activate_user_email_text']);
		$lang['admin_activate_user_email_text'] = str_replace("[login_link]", $settings['forum_address']."index.php?mode=login", $lang['admin_activate_user_email_text']);



```

**Comment by homebrewhops** [comment] 2017-12-11 18:49
Thank you. I've added the lines. The timeout still occurs and the error is now:
```
[Sat Dec 09 09:49:30.777668 2017] [:error] [pid 24321] [client 10.2.1.30:43244] PHP Notice:  Undefined variable: send_error in /var/www/website/board/includes/admin.inc.php on line 734, referer: https://fqdn/board/index.php?mode=admin&edit_user=8
[Mon Dec 11 13:45:20.861785 2017] [:error] [pid 5747] [client 10.2.1.30:50204] PHP Notice:  Undefined variable: send_error in /var/www/website/board/includes/admin.inc.php on line 736, referer: https://fqdn/board/index.php?mode=admin&edit_user=9
```

Also, the new user 'self' registration process itself produces the timeout. I don't see an error in apache so I'm not sure where the problem lies with that.

Steps: User Registers and Times Out, Admin clicks Activate User and the browser times out. At the end, apache logs produce the error above.

**Comment by derletztekick** [comment] 2017-12-11 21:16
Hi,

hmm, I cannot reproduce this error. I install a test-forum and select: "_self but new accounts have to be unlocked by an admin or a moderator_". 

A new test-user was added. This test-user got a mail that includes a activation-link. Clicking this link yields *not* in a timeout. Finally, an admin unlocked the new user - see attached screen shot. Again, no timeout.

![unlock](https://user-images.githubusercontent.com/3595603/33853664-03b08260-debf-11e7-9fe3-60b43c2169cc.png)

Can you explain, what you are doing step by step?

**Comment by auge8472** [comment] 2018-01-03 19:12
I tested the same procedure. User registers himself, verifies the account with the link in the e-mail and must wait for the activation of the account by an administrator. Every single step succeeds without an error. @homebrewhops I'm more interested in your PHP error log as in the Apache log. Are you willing to look into it and give us some insights?

The only way I can imagine is to have outdated language files because of a part of the error message in your first report (` …Undefined index: admin_activate_user_email_text in …`). If the index is undefined, the array element doesn't exist. And it exists with matching scripts and language files.So I'm willing to **assume** that *they **doesn't** match*.

**Comment by loesler** [comment] 2018-09-02 13:43
Because @homebrewhops  didn't answer the questions for more than five months, I assume the issue is solved or obsolete. Thatswhy I'll close it for now.

**Closed by loesler** 2018-09-02 13:43 UTC
Labels: bug
