### ISSUE TITLE
Honeypot suppresses registration of new users in my browser

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#324] opened 2018-01-05 10:13 UTC
Because of whatever in the registration form or processing I can not register as a new user in my own forum. I get an error message "Not all fields have been filled out" even I filled out every visible (`new_user_name`, `new_user_email`, `reg_pw` and `reg_pw_conf`) and leaved empty every honeypot field (`phone` and `repeat_email`). Surprisingly the honeypot field `repeat_email` gets the value of the admin accounts user name after sendig the form for the first time. This could be a browser issue.

The check for not filled fields in [line 59 of the `register.inc.php`](https://github.com/ilosuna/mylittleforum/blob/4354f5b6510321867b20e07e44e0ba115fc8ee4b/includes/register.inc.php#L59) seems to be broken. Is it correct to fail with an error in case of `!isset($_POST['repeat_email'])` or `!isset($_POST['phone'])`? My understanding of the honeypot is to leave the fields empty and not to make them mandatory.

**Comment by derletztekick** [comment] 2018-01-05 11:12
It works as designet. 

> My understanding of the honeypot is to leave the fields empty and not to make them mandatory.

If we don't check the existences of the fields, the protection is useless. Thus, the fields _must exist_ **and** be _empty_. Please do not report _bugs_ that cause by your individual template.

**Comment by derletztekick** [comment] 2018-01-05 12:05
> It's not a problem of my template.

Okay, I'm sorry, but I cannot reproduce the error. I add a new account _TestUserMicha_ to your project forum - it works. (You can delete the account) So, what should I do?

>  I tagged the issue not without cause as a question.

Yes, and I answered your question as best as possible. ;-)

**Comment by auge8472** [comment] 2018-01-05 12:30
> I cannot reproduce the error. I add a new account TestUserMicha to your project forum - it works. (You can delete the account) So, what should I do?

I've searched into the direction of "This could be a browser issue" and yes, with another browser I can create a new account. The last question is, why my browser fills one of the hidden fields and why with a non-matching value (a value that is typical for a name in a "repeat_email" named field) and how to prevent this. Read about [`autocomplete="off"` (german)](https://wiki.selfhtml.org/wiki/HTML/Formulare/Gestaltung#autocomplete) but I am discouraged by the list of browsers ignoring the attribute in this and that cases.

**Comment by derletztekick** [comment] 2018-01-05 12:34
The attribute `autocomplete` is invalid for XHTML, thus, we cannot use it within the default template.
FYI: I add the account with Opera browser. Should I check it with a specific browser, too?

**Comment by derletztekick** [comment] 2018-01-05 15:10
Edge works for me, too. Please delete the new test-account.

**Comment by auge8472** [comment] 2018-01-05 15:17
> The attribute autocomplete is invalid for XHTML, thus, we cannot use it within the default template.

Well, yes but: for *a valid reason* I would give a **\*pfft\*** about validity. ;-)

> FYI: I add the account with Opera browser. Should I check it with a specific browser, too?

No, I failed with a Firefox and succeeded with a Vivaldi (Chromium engine like opera too). But IMHO it is not an issue of the browser type but my browser *configuration*.

**Comment by derletztekick** [comment] 2018-01-05 15:39
I add a new user using FireFox. It works, too. It's seems to be a local problem of your system. Thus, I close this issue.

**Closed by derletztekick** 2018-01-05 15:39 UTC
Labels: question
