### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by motasim1** [ilosuna/mylittleforum#355] opened 2018-02-26 11:08 UTC
I get an error while trying to install the forum on my machine. It says: Error on line 58: Cannot find VERSION

**Comment by loesler** [comment] 2018-02-26 11:44
Please check, if [VERSION](https://github.com/ilosuna/mylittleforum/blob/master/config/VERSION) file is located in [config](https://github.com/ilosuna/mylittleforum/tree/master/config) directory.

**Comment by motasim1** [comment] 2018-02-26 12:56
It is there, but it still gives me that error.

**Comment by loesler** [comment] 2018-02-26 13:32
At line 58, the install script checks the existence of '../config/VERSION' via [file_exists()](http://php.net/manual/en/function.file-exists.php). This function returns false and, thus, the script stops. Do you change some paths? Maybe, PHP has no permissions to read the folder.

**Comment by auge8472** [comment] 2018-02-26 17:59
I read about the return values of the function [`file_exists` in the manual](https://secure.php.net/manual/en/function.file-exists.php). Should be either `true`, when the specified file exists or will be `false` …

1. … when the file does not exist, or …
2. … when a symlink points to a non existing file, or …
3. … when the file is not accessible because of safe mode.

When @motasim1 says, the file `VERSION` exists in the specified directory `config` –and he said that it exists there– the first case does not apply. This leads to the second point which looks very implausible to me. Why should a directory, created with a (S)FTP upload (assumedly a few minutes before the error occured) be or contain a symlinked non existing file, when the file itself was also uploaded in the same task? Why should the file be symlinked at all? This leaves the third point. Following the manuals link to [safe mode](https://secure.php.net/manual/en/features.safe-mode.php), this feature was removed with PHP 5.4. It should not be possible to run into this issue when the trigger isn't present anymore. So the third point can not causing the problem.

And, not to forget, why nobody else ran into this issue before? The questionable code block wasn't changed since the 2.3.99.x-betas. Even if we assume, that the most downloads are for updates and not for new installations, it's not plausible, that there are absolutely *no* new installations on the whole with exception of motasim1's. I tested this for myself a few times with different sub versions of the 2.4.x-branch and never ran into this problem. The whole issue sounds very odd.

@motasim1 Can you please add a screenshot of the file list of the forums subdirectory `config` from your FTP-client?

**Comment by auge8472** [comment] 2018-08-05 18:26
Because @motasim1 didn't answer the questions for more than five months, I assume the issue is solved or obsolete. Thatswhy I'll close it for now.

**Closed by auge8472** 2018-08-05 18:26 UTC
Labels: help wanted, question
